/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as GIdRouteImport } from './routes/g/$id'
import { Route as DashboardGamesIndexRouteImport } from './routes/dashboard/games/index'
import { Route as DashboardGamesIdRouteImport } from './routes/dashboard/games/$id'
import { Route as DashboardGamesIdIndexRouteImport } from './routes/dashboard/games/$id/index'
import { Route as DashboardGamesIdConfigRouteImport } from './routes/dashboard/games/$id/config'
import { Route as DashboardGamesIdBoardsRouteImport } from './routes/dashboard/games/$id/boards'
import { Route as DashboardGamesIdAnalyticsRouteImport } from './routes/dashboard/games/$id/analytics'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const GIdRoute = GIdRouteImport.update({
  id: '/g/$id',
  path: '/g/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGamesIndexRoute = DashboardGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGamesIdRoute = DashboardGamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGamesIdIndexRoute = DashboardGamesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardGamesIdRoute,
} as any)
const DashboardGamesIdConfigRoute = DashboardGamesIdConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => DashboardGamesIdRoute,
} as any)
const DashboardGamesIdBoardsRoute = DashboardGamesIdBoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => DashboardGamesIdRoute,
} as any)
const DashboardGamesIdAnalyticsRoute =
  DashboardGamesIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardGamesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/g/$id': typeof GIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/dashboard/games/$id': typeof DashboardGamesIdRouteWithChildren
  '/dashboard/games/': typeof DashboardGamesIndexRoute
  '/dashboard/games/$id/analytics': typeof DashboardGamesIdAnalyticsRoute
  '/dashboard/games/$id/boards': typeof DashboardGamesIdBoardsRoute
  '/dashboard/games/$id/config': typeof DashboardGamesIdConfigRoute
  '/dashboard/games/$id/': typeof DashboardGamesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/g/$id': typeof GIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/dashboard/games': typeof DashboardGamesIndexRoute
  '/dashboard/games/$id/analytics': typeof DashboardGamesIdAnalyticsRoute
  '/dashboard/games/$id/boards': typeof DashboardGamesIdBoardsRoute
  '/dashboard/games/$id/config': typeof DashboardGamesIdConfigRoute
  '/dashboard/games/$id': typeof DashboardGamesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/g/$id': typeof GIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/dashboard/games/$id': typeof DashboardGamesIdRouteWithChildren
  '/dashboard/games/': typeof DashboardGamesIndexRoute
  '/dashboard/games/$id/analytics': typeof DashboardGamesIdAnalyticsRoute
  '/dashboard/games/$id/boards': typeof DashboardGamesIdBoardsRoute
  '/dashboard/games/$id/config': typeof DashboardGamesIdConfigRoute
  '/dashboard/games/$id/': typeof DashboardGamesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/g/$id'
    | '/dashboard/'
    | '/login/'
    | '/dashboard/games/$id'
    | '/dashboard/games/'
    | '/dashboard/games/$id/analytics'
    | '/dashboard/games/$id/boards'
    | '/dashboard/games/$id/config'
    | '/dashboard/games/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/g/$id'
    | '/dashboard'
    | '/login'
    | '/dashboard/games'
    | '/dashboard/games/$id/analytics'
    | '/dashboard/games/$id/boards'
    | '/dashboard/games/$id/config'
    | '/dashboard/games/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/g/$id'
    | '/dashboard/'
    | '/login/'
    | '/dashboard/games/$id'
    | '/dashboard/games/'
    | '/dashboard/games/$id/analytics'
    | '/dashboard/games/$id/boards'
    | '/dashboard/games/$id/config'
    | '/dashboard/games/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  GIdRoute: typeof GIdRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/g/$id': {
      id: '/g/$id'
      path: '/g/$id'
      fullPath: '/g/$id'
      preLoaderRoute: typeof GIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/games/': {
      id: '/dashboard/games/'
      path: '/games'
      fullPath: '/dashboard/games/'
      preLoaderRoute: typeof DashboardGamesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/games/$id': {
      id: '/dashboard/games/$id'
      path: '/games/$id'
      fullPath: '/dashboard/games/$id'
      preLoaderRoute: typeof DashboardGamesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/games/$id/': {
      id: '/dashboard/games/$id/'
      path: '/'
      fullPath: '/dashboard/games/$id/'
      preLoaderRoute: typeof DashboardGamesIdIndexRouteImport
      parentRoute: typeof DashboardGamesIdRoute
    }
    '/dashboard/games/$id/config': {
      id: '/dashboard/games/$id/config'
      path: '/config'
      fullPath: '/dashboard/games/$id/config'
      preLoaderRoute: typeof DashboardGamesIdConfigRouteImport
      parentRoute: typeof DashboardGamesIdRoute
    }
    '/dashboard/games/$id/boards': {
      id: '/dashboard/games/$id/boards'
      path: '/boards'
      fullPath: '/dashboard/games/$id/boards'
      preLoaderRoute: typeof DashboardGamesIdBoardsRouteImport
      parentRoute: typeof DashboardGamesIdRoute
    }
    '/dashboard/games/$id/analytics': {
      id: '/dashboard/games/$id/analytics'
      path: '/analytics'
      fullPath: '/dashboard/games/$id/analytics'
      preLoaderRoute: typeof DashboardGamesIdAnalyticsRouteImport
      parentRoute: typeof DashboardGamesIdRoute
    }
  }
}

interface DashboardGamesIdRouteChildren {
  DashboardGamesIdAnalyticsRoute: typeof DashboardGamesIdAnalyticsRoute
  DashboardGamesIdBoardsRoute: typeof DashboardGamesIdBoardsRoute
  DashboardGamesIdConfigRoute: typeof DashboardGamesIdConfigRoute
  DashboardGamesIdIndexRoute: typeof DashboardGamesIdIndexRoute
}

const DashboardGamesIdRouteChildren: DashboardGamesIdRouteChildren = {
  DashboardGamesIdAnalyticsRoute: DashboardGamesIdAnalyticsRoute,
  DashboardGamesIdBoardsRoute: DashboardGamesIdBoardsRoute,
  DashboardGamesIdConfigRoute: DashboardGamesIdConfigRoute,
  DashboardGamesIdIndexRoute: DashboardGamesIdIndexRoute,
}

const DashboardGamesIdRouteWithChildren =
  DashboardGamesIdRoute._addFileChildren(DashboardGamesIdRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGamesIdRoute: typeof DashboardGamesIdRouteWithChildren
  DashboardGamesIndexRoute: typeof DashboardGamesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGamesIdRoute: DashboardGamesIdRouteWithChildren,
  DashboardGamesIndexRoute: DashboardGamesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  GIdRoute: GIdRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
